# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_auto_20180210_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
