# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_auto_20180210_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
