# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_auto_20180213_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='starts_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Starts'),
        ),
    ]
