# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_auto_20180213_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Location'),
        ),
    ]
