# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_auto_20180213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image_list',
            field=models.ImageField(blank=True, null=True, upload_to='media/vacancies/'),
        ),
    ]
